#define HAVE_OFF_T
#define G_OS_WIN32
#define ARCHEP_OS_WINDOWS
#define WINDOWS_COMPILE
#define _CRT_SECURE_NO_WARNINGS
#define VERSION "1.2.3.4"
#define VERSION_RC_NUMBER 1,2,3,4
#define HAVE_INTTYPES_H
#define HAVE_OFF_T_IN_SYS_TYPES
#define WINDOWS_COMPILE
#define G_OS_WIN32

#define DEBUG_IEC_DRV_WRITE(x)
#define DEBUG_IEC_BUS_WRITE(x)
#define DEBUG_IEC_DRV_READ(x)
#define DEBUG_IEC_BUS_READ(x)
#define STATIC_ASSERT(x)


#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdint.h>
#include <types.h>
#include <stdio.h>
#include <stdlib.h>
#include <io.h>



typedef void *GCallback();
typedef int GtkAccelGroup;
typedef int GdkModifierType;
typedef int GtkAccelFlags;
typedef int GClosure;
typedef int GtkWidget;

#define G_BEGIN_DECLS
#define G_GNUC_CONST
#define G_GNUC_UNUSED
#define GLIB_DEPRECATED_TYPE_IN_2_62_FOR(x)
#define GLIB_AVAILABLE_IN_ALL
#define GLIB_AVAILABLE_IN_2_76
#define GLIB_AVAILABLE_IN_2_64
#define GLIB_AVAILABLE_IN_2_62
#define GLIB_AVAILABLE_IN_2_74
#define GLIB_AVAILABLE_IN_2_58
#define GLIB_AVAILABLE_IN_2_40
#define GLIB_AVAILABLE_IN_2_54
#define GLIB_VERSION_MIN_REQUIRED 1
#define GLIB_AVAILABLE_IN_2_30
#define GLIB_DEPRECATED_IN_2_30_FOR(x)
#define GLIB_AVAILABLE_IN_2_68
#define GLIB_AVAILABLE_IN_2_70
#define GLIB_AVAILABLE_IN_2_72
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_74
#define GLIB_DEPRECATED_IN_2_30_FOR(x)
#define GLIB_DEPRECATED_TYPE_IN_2_32
#define GLIB_DEPRECATED
#define GLIB_AVAILABLE_IN_2_32
#define GLIB_AVAILABLE_IN_2_80
#define GLIB_AVAILABLE_IN_2_36
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_44
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_60
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_62
#define GLIB_DEPRECATED_FOR(x)
#define GLIB_AVAILABLE_IN_2_46
#define GLIB_DEPRECATED_IN_2_68_FOR(x)
#define GLIB_DEPRECATED_IN_2_62_FOR(x)
#define GLIB_AVAILABLE_IN_2_56
#define GLIB_AVAILABLE_IN_2_66
#define GLIB_DEPRECATED_IN_2_66_FOR(x)
#define GLIB_AVAILABLE_IN_2_34
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_66
#define GLIB_DEPRECATED_IN_2_46
#define GLIB_VAR
#define GLIB_AVAILABLE_IN_2_50
#define GLIB_AVAILABLE_TYPE_IN_2_72
#define GLIB_AVAILABLE_TYPE_IN_2_64
#define GLIB_DEPRECATED_IN_2_58_FOR(x)
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_64
#define GLIB_DEPRECATED_IN_2_28_FOR(x)
#define GLIB_AVAILABLE_IN_2_78
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_70
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_70
#define GLIB_DEPRECATED_IN_2_30
#define GLIB_AVAILABLE_IN_2_60
#define GLIB_AVAILABLE_IN_2_52
#define GLIB_AVAILABLE_IN_2_44
#define GLIB_AVAILABLE_STATIC_INLINE_IN_2_76
#define GLIB_AVAILABLE_IN_2_38
#define GLIB_DEPRECATED_IN_2_38_FOR(x)
#define GLIB_DEPRECATED_IN_2_44
#define GLIB_DEPRECATED_IN_2_70_FOR(x)
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_74
#define GLIB_AVAILABLE_IN_2_48
#define GLIB_DEPRECATED_IN_2_34
#define GLIB_DEPRECATED_ENUMERATOR_IN_2_32_FOR(x)
#define GLIB_DEPRECATED_TYPE_IN_2_38_FOR(x)
#define GLIB_DEPRECATED_IN_2_62
#define GLIB_DEPRECATED_TYPE_IN_2_48
#define GLIB_DEPRECATED_IN_2_48
#define GLIB_AVAILABLE_TYPE_IN_2_66
#define GLIB_AVAILABLE_ENUMERATOR_IN_2_68
#define GLIB_DEPRECATED_TYPE_IN_2_26_FOR(x)
#define GLIB_DEPRECATED_TYPE_IN_2_26
#define GLIB_DEPRECATED_IN_2_26
#define GLIB_DEPRECATED_IN_2_32_FOR(x)
#define GLIB_DEPRECATED_IN_2_32
#define GLIB_DEPRECATED_MACRO_IN_2_32
#define GLIB_DEPRECATED_TYPE_IN_2_32_FOR(x)
#define GLIB_DEPRECATED_MACRO_IN_2_32_FOR(x)
